exports.seed = async function (knex) {
  // desc: truncate all existing tables
  await knex.raw('TRUNCATE TABLE "errors" CASCADE');

  await knex("errors").insert([
    {
      fault: "fake fault1",
      solution: ["fake solution1", "fake solution2"],
      cause: ["fake cause1", "fake cause2"],
      type: "fake type",
      subtype: "fake sub",
      severity: "fake severity",
      desc: "in keren or we trust",
    },
    {
      fault: "fake fault2",
      solution: ["fake solution1", "fake solution2"],
      cause: ["fake cause1", "fake cause2"],
      type: "fake type",
      subtype: "fake sub",
      severity: "fake severity",
      desc: "in keren or we trust",
    },
    {
      fault: "fake fault3",
      solution: ["fake solution1", "fake solution2"],
      cause: ["fake cause1", "fake cause2"],
      type: "fake type",
      subtype: "fake sub",
      severity: "fake severity",
      desc: "in keren or we trust",
    },
    {
      fault: "fake fault4",
      solution: ["fake solution1", "fake solution2"],
      cause: ["fake cause1", "fake cause2"],
      type: "fake type",
      subtype: "fake sub",
      severity: "fake severity",
      desc: "in keren or we trust",
    },
    {
      fault: "fake fault5",
      solution: ["fake solution1", "fake solution2"],
      cause: ["fake cause1", "fake cause2"],
      type: "fake type",
      subtype: "fake sub",
      severity: "fake severity",
      desc: "in keren or we trust",
    },
    {
      fault: "fake fault6",
      solution: ["fake solution1", "fake solution2"],
      cause: ["fake cause1", "fake cause2"],
      type: "fake type",
      subtype: "fake sub",
      severity: "fake severity",
      desc: "in keren or we trust",
    },
    {
      fault: "fake fault7",
      solution: ["fake solution1", "fake solution2"],
      cause: ["fake cause1", "fake cause2"],
      type: "fake type",
      subtype: "fake sub",
      severity: "fake severity",
      desc: "in keren or we trust",
    },
    {
      fault: "fake fault8",
      solution: ["fake solution1", "fake solution2"],
      cause: ["fake cause1", "fake cause2"],
      type: "fake type",
      subtype: "fake sub",
      severity: "fake severity",
      desc: "in keren or we trust",
    },
    {
      fault: "fake fault9",
      solution: ["fake solution1", "fake solution2"],
      cause: ["fake cause1", "fake cause2"],
      type: "fake type",
      subtype: "fake sub",
      severity: "fake severity",
      desc: "in keren or we trust",
    },
    {
      fault: "fake fault10",
      solution: ["fake solution1", "fake solution2"],
      cause: ["fake cause1", "fake cause2"],
      type: "fake type",
      subtype: "fake sub",
      severity: "fake severity",
      desc: "in keren or we trust",
    },
  ]);
};
